# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_deploy:
- R CMD INSTALL $PKG_TARBALL
- Rscript -e "vbzdelays::render_site()"
- touch _site/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT # Set in the settings page of your repository, as a secure variable
  local_dir: _site
  on:
    branch: master
